#frozen_string_literal: true

# source "https://rubygems.org"

# gem "allure-cucumber", "2.13.6.4"
# gem "cucumber", "5.2"
# gem "capybara", "3.33"
# gem "selenium-webdriver", "3.142.7"
# gem "rspec", "3.10"
# gem "faker", "2.14"
# gem "mongo", "2.13.1"
# gem "webdrivers", "~> 4.0", require: false

source "https://rubygems.org"

gem "cucumber", "5.2"
gem "rspec", "3.10"
gem "selenium-webdriver"
gem "capybara", "3.35.3"
gem "site_prism", "3.7.3"
gem "chromedriver-helper"
gem "ffi"
gem "pry"
gem "mysql2"
gem "date"
gem "net-ssh-gateway", "2.0.0"
gem "allure-cucumber", "2.15"
gem "faker", "2.19"
gem "mongo", "2.13.1"
gem "webdrivers", "~> 4.0", require: false
gem "oj", "3.13.9"
